---
- hosts: all
  sudo: true
  roles:
    - common
  vars:
    post: "post.php"

  tasks:
    - name: Insert all posts into MySQL database
      shell: "python {{ document_root }}/posts/insert_posts.py {{ document_root }}/posts/posts/{{ post }}"

