---
- hosts: all
  sudo: true
  vars:
    server_name: "default:80"
    repository_url: "https://github.com/kylebebak/dronfelipe.git"
    repository_root: /var/www/dronfelipe
    document_root: "{{ repository_root }}/html"
    mysql_root_password: root
    production: true

  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded

  tasks:
    - name: Clean /var/lib/apt/lists/
      shell: rm /var/lib/apt/lists/* -vf
      ignore_errors: yes

    - name: Update apt cache
      apt: update_cache=yes

    - name: Pull latest commits from Github
      git:
        repo={{ repository_url }}
        dest={{ repository_root }}
        clone=no
        update=yes
      when:
        production
      notify:
        - reload apache
